title: Algorithms
description: Repository with the implementation (in Python) and description of several computational, mathematical and statistical algorithms
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
